/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/comment/': RouteRecordInfo<'/comment/', '/comment', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/s001': RouteRecordInfo<'/posts/s001', '/posts/s001', Record<never, never>, Record<never, never>>,
    '/posts/s002': RouteRecordInfo<'/posts/s002', '/posts/s002', Record<never, never>, Record<never, never>>,
    '/posts/s003': RouteRecordInfo<'/posts/s003', '/posts/s003', Record<never, never>, Record<never, never>>,
    '/posts/s004': RouteRecordInfo<'/posts/s004', '/posts/s004', Record<never, never>, Record<never, never>>,
    '/posts/s005': RouteRecordInfo<'/posts/s005', '/posts/s005', Record<never, never>, Record<never, never>>,
    '/posts/s006': RouteRecordInfo<'/posts/s006', '/posts/s006', Record<never, never>, Record<never, never>>,
    '/posts/s007': RouteRecordInfo<'/posts/s007', '/posts/s007', Record<never, never>, Record<never, never>>,
    '/posts/s008': RouteRecordInfo<'/posts/s008', '/posts/s008', Record<never, never>, Record<never, never>>,
    '/posts/s009': RouteRecordInfo<'/posts/s009', '/posts/s009', Record<never, never>, Record<never, never>>,
    '/posts/s010': RouteRecordInfo<'/posts/s010', '/posts/s010', Record<never, never>, Record<never, never>>,
    '/posts/theone': RouteRecordInfo<'/posts/theone', '/posts/theone', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
